### ISSUE TITLE
apk should be placed in releases

### ISSUE THREAD

**Issue by l2dy** [zhoubowen-sky/LingDong2.0#3]
https://github.com/zhoubowen-sky/LingDong2.0/releases

**Comment by zhoubowen-sky** [comment]
@l2dy  Thank you for your advice ,  I'm a new fish in Github , I will modify it later.

**Comment by jp1017** [comment]
add tag and drag apk to it. :smile:

**Comment by l2dy** [comment]
Feel free to close this issue if the repo is archived.

**Comment by l2dy** [comment]
Closed due to inactivity.
